
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -38;
const int acc_off_y = -333;
const int acc_off_z = 286;
const float acc_scale_x = 16403.223440;
const float acc_scale_y = 16431.618084;
const float acc_scale_z = 16665.953642;

const int magn_off_x = -75;
const int magn_off_y = 122;
const int magn_off_z = -62;
const float magn_scale_x = 96.848023;
const float magn_scale_y = 119.485323;
const float magn_scale_z = 133.704461;
